name: Deploy on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Install SSH key # Installer une clé privée SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

      - name: Add server's SSH key to known_hosts 
        run: ssh-keyscan -H 185.98.139.228 >> ~/.ssh/known_hosts
        
      - name: Deploy files via SSH
        run: rsync -avz --delete ./ root@185.98.139.228:/var/www/pwa_nathan_bricard
