name: Deploy on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Install SSH key # Installer une clé privée SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

      - name: Add server's SSH key to known_hosts 
        run: ssh-keyscan -H 185.98.139.228 >> ~/.ssh/known_hosts
        
      - name: Deploy files on server, install and build
        run: |
            ssh root@185.98.139.228 << 'EOF'
            cd /var/www/pwa_nathan_bricard
            git pull origin main
            npm install
            npm run build
            pm2 restart pwa_nathan_bricard || pm2 start npm --name "pwa_nathan_bricard" -- start
            EOF



